version: '3.5'

services:
  jenkins:
    image: genki_jenkins
    build:
      context: ./image
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    ports:
      - 8443:8080
    privileged: true
    environment:
      JENKINS_OPTS: '--prefix=/jenkins'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home:
    external: true
